name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod install
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Archive iOS App
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     | tee xcodebuild.log | xcpretty

      - name: Check xcodebuild log
        run: tail -n 50 xcodebuild.log

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath build/ios/iphoneos/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios/iphoneos \
                     | tee export.log | xcpretty

      - name: Check export log
        run: tail -n 50 export.log

      - name: List contents of build directory
        run: ls -R build/ios/iphoneos

      - name: Check if IPA file exists
        run: |
          if [ -f build/ios/iphoneos/Runner.ipa ]; then
            echo "IPA file exists."
          else
            echo "IPA file does not exist."
            exit 1
          fi

      - name: Upload binaries to release
        if: success() # Only run this if the previous steps succeeded
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/Runner.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
