name: Build and Deploy iOS App to Appetize.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: macos-latest

    permissions:
      contents: write # Allows creating and pushing tags
      actions: read # Allows reading repository actions metadata

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v3
        with:
          xcode-version: '14.2' # Replace with your Xcode version

      - name: Build the iOS app
        run: |
          xcodebuild -workspace YourWorkspace.xcworkspace \
                     -scheme YourScheme \
                     -sdk iphoneos \
                     -configuration Release \
                     archive \
                     -archivePath ${{ github.workspace }}/build/YourApp.xcarchive

      - name: Export the IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ${{ github.workspace }}/build/YourApp.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath ${{ github.workspace }}/build

      - name: Create Tag
        id: create-tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA to Appetize.io
        env:
          APPETIZE_API_KEY: ${{ secrets.APPETIZE_API_KEY }}
        run: |
          curl -F 'file=@${{ github.workspace }}/build/YourApp.ipa' \
               -F 'name=YourApp' \
               -F 'description=App built by GitHub Actions' \
               -F 'platform=ios' \
               -H "Authorization: Bearer $APPETIZE_API_KEY" \
               https://api.appetize.io/v1/apps
