name: iOS Simulator Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build for Simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Archive the .app bundle for simulator
        run: |
          cd build/ios/iphonesimulator
          zip -r FlutterApp.zip Runner.app

      - name: Upload .app bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp.zip
          path: build/ios/iphonesimulator/FlutterApp.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphonesimulator/FlutterApp.zip
          tag: v1.0  # Update this tag as needed
          overwrite: true
          body: "This is the first release of the simulator build"
