name: iOS Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Archive the .app bundle
        run: |
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos
          zip -r FlutterApp.zip Payload/Runner.app

      - name: Upload .app bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp.zip
          path: build/ios/iphoneos/FlutterApp.zip
